package MonAppliMessagerie;


/**
* MonAppliMessagerie/_ACStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public class _ACStub extends org.omg.CORBA.portable.ObjectImpl implements MonAppliMessagerie.AC
{

  public MonAppliMessagerie.Certificat getCertificat ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCertificat", true);
                $in = _invoke ($out);
                MonAppliMessagerie.Certificat $result = MonAppliMessagerie.CertificatHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCertificat (        );
            } finally {
                _releaseReply ($in);
            }
  } // getCertificat

  public void enregistrer (String clePublique, short idPorteur, String dateExpiration, String usage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrer", true);
                $out.write_string (clePublique);
                $out.write_short (idPorteur);
                $out.write_string (dateExpiration);
                $out.write_string (usage);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrer (clePublique, idPorteur, dateExpiration, usage        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrer

  public void revoquerCertificat (MonAppliMessagerie.Certificat certificatPorteur, short id, String periode) throws MonAppliMessagerie.certif_revoque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("revoquerCertificat", true);
                MonAppliMessagerie.CertificatHelper.write ($out, certificatPorteur);
                $out.write_short (id);
                $out.write_string (periode);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MonAppliMessagerie/certif_revoque:1.0"))
                    throw MonAppliMessagerie.certif_revoqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                revoquerCertificat (certificatPorteur, id, periode        );
            } finally {
                _releaseReply ($in);
            }
  } // revoquerCertificat

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MonAppliMessagerie/AC:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ACStub
