package MonAppliMessagerie;


/**
* MonAppliMessagerie/_AEStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 f�vrier 2015 14 h 55 CET
*/

public class _AEStub extends org.omg.CORBA.portable.ObjectImpl implements MonAppliMessagerie.AE
{

  public MonAppliMessagerie.Certificat saveCertificat (String clepublique, short id, String mdp, String dateExpiration, String usage) throws MonAppliMessagerie.erreur_authent
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("saveCertificat", true);
                $out.write_string (clepublique);
                $out.write_short (id);
                $out.write_string (mdp);
                $out.write_string (dateExpiration);
                $out.write_string (usage);
                $in = _invoke ($out);
                MonAppliMessagerie.Certificat $result = MonAppliMessagerie.CertificatHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MonAppliMessagerie/erreur_authent:1.0"))
                    throw MonAppliMessagerie.erreur_authentHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return saveCertificat (clepublique, id, mdp, dateExpiration, usage        );
            } finally {
                _releaseReply ($in);
            }
  } // saveCertificat


  // l'AE authentifie puis relaye la demande de revocation
  public void revoquer (MonAppliMessagerie.Certificat certificatPorteur, short id, String mdp, String periode)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("revoquer", true);
                MonAppliMessagerie.CertificatHelper.write ($out, certificatPorteur);
                $out.write_short (id);
                $out.write_string (mdp);
                $out.write_string (periode);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                revoquer (certificatPorteur, id, mdp, periode        );
            } finally {
                _releaseReply ($in);
            }
  } // revoquer


  // l'AE renvoi le certificat créé à l'appli Porteur qui avait demandé l'enregistrement
  public void publier (MonAppliMessagerie.Certificat certificatPorteur)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("publier", true);
                MonAppliMessagerie.CertificatHelper.write ($out, certificatPorteur);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                publier (certificatPorteur        );
            } finally {
                _releaseReply ($in);
            }
  } // publier

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MonAppliMessagerie/AE:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AEStub
