package MonAppliMessagerie;


/**
* MonAppliMessagerie/ACOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public interface ACOperations 
{
  MonAppliMessagerie.Certificat getCertificat ();
  void enregistrer (String clePublique, short idPorteur, String dateExpiration, String usage);
  void revoquerCertificat (MonAppliMessagerie.Certificat certificatPorteur, short id, String periode) throws MonAppliMessagerie.certif_revoque;
} // interface ACOperations
