package MonAppliMessagerie;

/**
* MonAppliMessagerie/AEHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class AEHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.AE value = null;

  public AEHolder ()
  {
  }

  public AEHolder (MonAppliMessagerie.AE initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.AEHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.AEHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.AEHelper.type ();
  }

}
