package MonAppliMessagerie;

/**
* MonAppliMessagerie/AVHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class AVHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.AV value = null;

  public AVHolder ()
  {
  }

  public AVHolder (MonAppliMessagerie.AV initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.AVHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.AVHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.AVHelper.type ();
  }

}
