package MonAppliMessagerie;


/**
* MonAppliMessagerie/AVOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 f�vrier 2015 14 h 55 CET
*/

public interface AVOperations 
{
  MonAppliMessagerie.Certificat getCertificatAC ();
  void verifierRevocation (MonAppliMessagerie.Certificat certifCourant) throws MonAppliMessagerie.erreur_certif, MonAppliMessagerie.certif_revoque;

  // AC pousse à l'AV la mise à jour de la LCR
  void revoquerCertificat (MonAppliMessagerie.Certificat certificatPorteur, short id, String periode);
} // interface AVOperations
