package MonAppliMessagerie;


/**
* MonAppliMessagerie/AVPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 f�vrier 2015 14 h 55 CET
*/

public abstract class AVPOA extends org.omg.PortableServer.Servant
 implements MonAppliMessagerie.AVOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCertificatAC", new java.lang.Integer (0));
    _methods.put ("verifierRevocation", new java.lang.Integer (1));
    _methods.put ("revoquerCertificat", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MonAppliMessagerie/AV/getCertificatAC
       {
         MonAppliMessagerie.Certificat $result = null;
         $result = this.getCertificatAC ();
         out = $rh.createReply();
         MonAppliMessagerie.CertificatHelper.write (out, $result);
         break;
       }

       case 1:  // MonAppliMessagerie/AV/verifierRevocation
       {
         try {
           MonAppliMessagerie.Certificat certifCourant = MonAppliMessagerie.CertificatHelper.read (in);
           this.verifierRevocation (certifCourant);
           out = $rh.createReply();
         } catch (MonAppliMessagerie.erreur_certif $ex) {
           out = $rh.createExceptionReply ();
           MonAppliMessagerie.erreur_certifHelper.write (out, $ex);
         } catch (MonAppliMessagerie.certif_revoque $ex) {
           out = $rh.createExceptionReply ();
           MonAppliMessagerie.certif_revoqueHelper.write (out, $ex);
         }
         break;
       }


  // AC pousse à l'AV la mise à jour de la LCR
       case 2:  // MonAppliMessagerie/AV/revoquerCertificat
       {
         MonAppliMessagerie.Certificat certificatPorteur = MonAppliMessagerie.CertificatHelper.read (in);
         short id = in.read_short ();
         String periode = in.read_string ();
         this.revoquerCertificat (certificatPorteur, id, periode);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MonAppliMessagerie/AV:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AV _this() 
  {
    return AVHelper.narrow(
    super._this_object());
  }

  public AV _this(org.omg.CORBA.ORB orb) 
  {
    return AVHelper.narrow(
    super._this_object(orb));
  }


} // class AVPOA
