package MonAppliMessagerie;


/**
* MonAppliMessagerie/certif_revoque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class certif_revoque extends org.omg.CORBA.UserException
{
  public String certificat_revoque = null;
  public short id = (short)0;

  public certif_revoque ()
  {
    super(certif_revoqueHelper.id());
  } // ctor

  public certif_revoque (String _certificat_revoque, short _id)
  {
    super(certif_revoqueHelper.id());
    certificat_revoque = _certificat_revoque;
    id = _id;
  } // ctor


  public certif_revoque (String $reason, String _certificat_revoque, short _id)
  {
    super(certif_revoqueHelper.id() + "  " + $reason);
    certificat_revoque = _certificat_revoque;
    id = _id;
  } // ctor

} // class certif_revoque
