package MonAppliMessagerie;


/**
* MonAppliMessagerie/CertificatHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

abstract public class CertificatHelper
{
  private static String  _id = "IDL:MonAppliMessagerie/Certificat:1.0";

  public static void insert (org.omg.CORBA.Any a, MonAppliMessagerie.Certificat that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MonAppliMessagerie.Certificat extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "IOR_AV",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "Num_Unique",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ValiditeDebut",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ValiditeFin",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "ClePubClient",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "usage",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "Signature",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (MonAppliMessagerie.CertificatHelper.id (), "Certificat", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MonAppliMessagerie.Certificat read (org.omg.CORBA.portable.InputStream istream)
  {
    MonAppliMessagerie.Certificat value = new MonAppliMessagerie.Certificat ();
    value.IOR_AV = istream.read_string ();
    value.Num_Unique = istream.read_short ();
    value.ValiditeDebut = istream.read_string ();
    value.ValiditeFin = istream.read_string ();
    value.ClePubClient = istream.read_string ();
    value.usage = istream.read_string ();
    value.Signature = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MonAppliMessagerie.Certificat value)
  {
    ostream.write_string (value.IOR_AV);
    ostream.write_short (value.Num_Unique);
    ostream.write_string (value.ValiditeDebut);
    ostream.write_string (value.ValiditeFin);
    ostream.write_string (value.ClePubClient);
    ostream.write_string (value.usage);
    ostream.write_string (value.Signature);
  }

}
