package MonAppliMessagerie;

/**
* MonAppliMessagerie/CertificatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class CertificatHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.Certificat value = null;

  public CertificatHolder ()
  {
  }

  public CertificatHolder (MonAppliMessagerie.Certificat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.CertificatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.CertificatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.CertificatHelper.type ();
  }

}
