package MonAppliMessagerie;


/**
* MonAppliMessagerie/Certificat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class Certificat implements org.omg.CORBA.portable.IDLEntity
{
  public String IOR_AV = null;
  public short Num_Unique = (short)0;
  public String ValiditeDebut = null;
  public String ValiditeFin = null;
  public String ClePubClient = null;
  public String usage = null;

  // enum?
  public String Signature = null;

  public Certificat ()
  {
  } // ctor

  public Certificat (String _IOR_AV, short _Num_Unique, String _ValiditeDebut, String _ValiditeFin, String _ClePubClient, String _usage, String _Signature)
  {
    IOR_AV = _IOR_AV;
    Num_Unique = _Num_Unique;
    ValiditeDebut = _ValiditeDebut;
    ValiditeFin = _ValiditeFin;
    ClePubClient = _ClePubClient;
    usage = _usage;
    Signature = _Signature;
  } // ctor

} // class Certificat
