package MonAppliMessagerie;

/**
* MonAppliMessagerie/certif_revoqueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class certif_revoqueHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.certif_revoque value = null;

  public certif_revoqueHolder ()
  {
  }

  public certif_revoqueHolder (MonAppliMessagerie.certif_revoque initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.certif_revoqueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.certif_revoqueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.certif_revoqueHelper.type ();
  }

}
