package MonAppliMessagerie;


/**
* MonAppliMessagerie/erreur_authent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class erreur_authent extends org.omg.CORBA.UserException
{
  public String erreur_authentification = null;
  public short id = (short)0;

  public erreur_authent ()
  {
    super(erreur_authentHelper.id());
  } // ctor

  public erreur_authent (String _erreur_authentification, short _id)
  {
    super(erreur_authentHelper.id());
    erreur_authentification = _erreur_authentification;
    id = _id;
  } // ctor


  public erreur_authent (String $reason, String _erreur_authentification, short _id)
  {
    super(erreur_authentHelper.id() + "  " + $reason);
    erreur_authentification = _erreur_authentification;
    id = _id;
  } // ctor

} // class erreur_authent
