package MonAppliMessagerie;


/**
* MonAppliMessagerie/erreur_authentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

abstract public class erreur_authentHelper
{
  private static String  _id = "IDL:MonAppliMessagerie/erreur_authent:1.0";

  public static void insert (org.omg.CORBA.Any a, MonAppliMessagerie.erreur_authent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MonAppliMessagerie.erreur_authent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "erreur_authentification",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (MonAppliMessagerie.erreur_authentHelper.id (), "erreur_authent", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MonAppliMessagerie.erreur_authent read (org.omg.CORBA.portable.InputStream istream)
  {
    MonAppliMessagerie.erreur_authent value = new MonAppliMessagerie.erreur_authent ();
    // read and discard the repository ID
    istream.read_string ();
    value.erreur_authentification = istream.read_string ();
    value.id = istream.read_short ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MonAppliMessagerie.erreur_authent value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.erreur_authentification);
    ostream.write_short (value.id);
  }

}
