package MonAppliMessagerie;

/**
* MonAppliMessagerie/erreur_authentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class erreur_authentHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.erreur_authent value = null;

  public erreur_authentHolder ()
  {
  }

  public erreur_authentHolder (MonAppliMessagerie.erreur_authent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.erreur_authentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.erreur_authentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.erreur_authentHelper.type ();
  }

}
