package MonAppliMessagerie;


/**
* MonAppliMessagerie/erreur_certif.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class erreur_certif extends org.omg.CORBA.UserException
{
  public String erreur_certification = null;
  public short id = (short)0;

  public erreur_certif ()
  {
    super(erreur_certifHelper.id());
  } // ctor

  public erreur_certif (String _erreur_certification, short _id)
  {
    super(erreur_certifHelper.id());
    erreur_certification = _erreur_certification;
    id = _id;
  } // ctor


  public erreur_certif (String $reason, String _erreur_certification, short _id)
  {
    super(erreur_certifHelper.id() + "  " + $reason);
    erreur_certification = _erreur_certification;
    id = _id;
  } // ctor

} // class erreur_certif
