package MonAppliMessagerie;


/**
* MonAppliMessagerie/Porteur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public interface Porteur extends PorteurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Porteur
