package MonAppliMessagerie;


/**
* MonAppliMessagerie/PorteurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 f�vrier 2015 14 h 55 CET
*/

public interface PorteurOperations 
{
  MonAppliMessagerie.Certificat getCertificatPorteur ();

  // cette méthode affiche les retours liés aux certifications
  void afficherMessage (String message);
} // interface PorteurOperations
