package MonAppliMessagerie;


/**
* MonAppliMessagerie/PorteurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 f�vrier 2015 14 h 55 CET
*/

public abstract class PorteurPOA extends org.omg.PortableServer.Servant
 implements MonAppliMessagerie.PorteurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getCertificatPorteur", new java.lang.Integer (0));
    _methods.put ("afficherMessage", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MonAppliMessagerie/Porteur/getCertificatPorteur
       {
         MonAppliMessagerie.Certificat $result = null;
         $result = this.getCertificatPorteur ();
         out = $rh.createReply();
         MonAppliMessagerie.CertificatHelper.write (out, $result);
         break;
       }


  // cette méthode affiche les retours liés aux certifications
       case 1:  // MonAppliMessagerie/Porteur/afficherMessage
       {
         String message = in.read_string ();
         this.afficherMessage (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MonAppliMessagerie/Porteur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Porteur _this() 
  {
    return PorteurHelper.narrow(
    super._this_object());
  }

  public Porteur _this(org.omg.CORBA.ORB orb) 
  {
    return PorteurHelper.narrow(
    super._this_object(orb));
  }


} // class PorteurPOA
