package MonAppliMessagerie;

/**
* MonAppliMessagerie/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public MonAppliMessagerie.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (MonAppliMessagerie.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MonAppliMessagerie.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MonAppliMessagerie.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MonAppliMessagerie.UserHelper.type ();
  }

}
