package MonAppliMessagerie;


/**
* MonAppliMessagerie/UserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from contrat.idl
* samedi 21 février 2015 14 h 55 CET
*/

public interface UserOperations 
{
  String afficherMessage (String message, boolean chiffred);
} // interface UserOperations
