module MonAppliMessagerie {
	exception erreur_authent {
		string erreur_authentification;
		short id;
	};

	exception erreur_certif {
		string erreur_certification;
		short id;
	};
	
	exception certif_revoque {
		string certificat_revoque;
		short id;		
	};

	struct Certificat {
		string proprietaire;
		string IOR_AV;
		short Num_Unique;
		string ValiditeDebut;
		string ValiditeFin;
		string ClePubClient;
		string usage; // enum?
		string Signature;
	};


	interface AE {
		Certificat saveCertificat(in string clepublique, in string proprietaire, in string mdp, in string dateExpiration, in string usage);
		
		// l'AE authentifie puis relaye la demande de revocation
		boolean revoquer(in Certificat certificatPorteur, in string mdp, in string periode);
		
		// l'AE renvoi le certificat créé à l'appli Porteur qui avait demandé l'enregistrement
		void publier(in Certificat certificatPorteur); 
	};

	interface AV {
		Certificat getCertificatAC();
		string verifierRevocation(in Certificat certifCourant);

		// AC pousse à l'AV la mise à jour de la LCR
		boolean revoquerCertificat(in Certificat certificatPorteur, in string periode); 
	};

	interface AC {
		Certificat getCertificat();
		Certificat enregistrer (in string clePublique, in string proprietaire, in string dateExpiration, in string usage);
		boolean revoquerCertificat (in Certificat certificatPorteur, in string periode);	
	};

	interface User {	
		string afficherMessage(in string sender, in string message, in boolean chiffred);
	};

	interface Porteur {	
		Certificat getCertificatPorteur();	
		
	};

};
// Fin Module